### ISSUE TITLE
Don't fail the build if CodeCov is down

### ISSUE THREAD

**Issue by alejandrovelez7** [codecov/codecov-circleci-orb#11]
The bash uploader docs suggest adding ` || echo 'Codecov failed to upload'` so that the bash uploader command always returns exit 0 and doesn't fail the build if CodeCov is down momentarily. 

https://docs.codecov.io/docs/about-the-codecov-bash-uploader

Should that be included into this orb? 

We do not currently use the orb, but have been bitten by this issue before in our circle yml. 

Let me know if you'd like me to suggest a PR.

**Comment by thomasrockhu** [comment]
@alejandrovelez7 great idea!  I'll slot that in this week

**Comment by teohhanhui** [comment]
Can be closed. Incidentally also fixed by #17. :smile:

**Comment by knoid** [comment]
Sorry but I actually want it to fail when it fails to upload. Is there a way we could make this configurable?
