### ISSUE TITLE
Public repo failing to upload w/o token

### ISSUE THREAD

**Issue by rpkilby** [codecov/codecov-circleci-orb#12]
I'm not sure if this is an issue in the codecov-bash or the orb, however, when a token is not provided (note that this is a pubic repo, so a token shouldn't be necessary), the `-y` commandline argument is passed as the token value. See the following example failure:

https://circleci.com/gh/rpkilby/tox-factor/54

```
https://codecov.io/upload/v4?package=bash-8a28df4&token=-y&branch=master&commit=6e360866d29e94fbeb3f4a058296e38139cf6638&build=54&build_url=&name=54&tag=&slug=rpkilby%2Ftox-factor&service=circleci&flags=&pr=&job=0
HTTP 400
Provided token is not a UUID.
```

The error being: `&token=-y`

**Comment by rpkilby** [comment]
Note that I've just opted to switch to codecov-python instead.

**Comment by teohhanhui** [comment]
Will be fixed by #17

**Comment by teohhanhui** [comment]
This can be closed, since #17 is merged and released.

**Comment by piotr-s-brainhub** [comment]
@teohhanhui 

I'm getting this error https://app.circleci.com/pipelines/github/brainhubeu/issue-overseer/90/workflows/0b729ee8-dc2d-4bb4-adf1-2394f9e30e4f/jobs/192 though the same token in the command line works.

**Comment by piotr-s-brainhub** [comment]
Sorry, I had `CODECOV_TOKEN` instead of `$CODECOV_TOKEN` in the CI config.
