### ISSUE TITLE
Upload failed: ["Repository not found"]

### ISSUE THREAD

**Issue by FredrikAugust** [codecov/codecov-circleci-orb#189]
Hey! We're trying to use the 4.0.1 Orb, but we're receiving this error during uploads. Is there a flag that needs to be set or something?

**Comment by FredrikAugust** [comment]
After setting `--slug` in `upload_args` we now get an error 

```
Upload failed: ["Commit SHA not found"]
```

Shouldn't it be able to decipher this from `CIRCLE_SHA1`?

**Comment by FredrikAugust** [comment]
```
./"codecov"  create-commit -t <redacted>
info - 2024-03-20 09:42:43,002 -- ci service found: circleci
info - 2024-03-20 09:42:43,074 -- Process Commit creating complete
error - 2024-03-20 09:42:43,074 -- Commit creating failed: ["Repository not found"]
./"codecov"  create-report -t <redacted>
```

We're also seeing the errors for other commands which we seemingly can't pass CLI args to. We're using a private repo on GitHub.

**Comment by FredrikAugust** [comment]
Aha. It seems like `CIRCLE_PROJECT_USERNAME` env var injected from CircleCI doesn't actually contain our username, but our display name. Is this a bug in CircleCI?

**Comment by joejacobs** [comment]
@FredrikAugust did you find a solution to this? Having the same issue.

**Comment by FredrikAugust** [comment]
Hi yeah we did!The circleci environment variable injected which indicates what org has the repo is wrong so manually overriding it works. I sadly don’t remember what it’s called but it should be quite easy to track down in the source codeEnviado desde mi iPhoneEl 24 mar 2024, a las 4:52, Joe Jacobs ***@***.***> escribió:﻿
@FredrikAugust did you find a solution to this? Having the same issue.
