### ISSUE TITLE
Add support for Codecov Enterprise

### ISSUE THREAD

**Issue by drazisil** [codecov/codecov-circleci-orb#19]
The orb should allow the url to be overridden for use with Codecov Enterprise.

**Comment by yihyang** [comment]
Hi @drazisil I would like to take this up

**Comment by yihyang** [comment]
Hi @drazisil I have created a PR here: https://github.com/codecov/codecov-circleci-orb/pull/23

Please let me know if there is any other changes needed. Thanks.

**Comment by drazisil** [comment]
@yihyang Looks great, thanks!

@KyleTryon Thanks for reviewing.
