### ISSUE TITLE
Convert 'token' parameter type from "string" to "env_var_name".

### ISSUE THREAD

**Issue by KyleTryon** [codecov/codecov-circleci-orb#22]
https://github.com/codecov/codecov-circleci-orb/blob/master/orb.yml#L22

Guide: https://circleci.com/docs/2.0/orbs-best-practices/#parameters

```
When possible, use defaults for parameters unless a user input is essential. Utilize the “env_var_name” parameter type to secure API keys or other sensitive data.
```
https://circleci.com/docs/2.0/reusing-config/#environment-variable-name

_Consider adding the `orbtoberfest` label on this issue to make this issue eligible for #Orbtoberfest https://circleci-public.github.io/hacktoberfest_

**Comment by piyush-insider** [comment]
@thomasrockhu Hey, I would like to pick this up.
