### ISSUE TITLE
Allow specifiying other commandline args

### ISSUE THREAD

**Issue by glenjamin** [codecov/codecov-circleci-orb#28]
It would be convinient if it were possible to pass arbitrary extra arguments to the command the orb wraps, perhaps via an `extra_args` parameter?

We keep seeing slow uploads of coverage data, and I'd like to add some curl timeouts to speed up retries - but this isn't currently exposed by the orb.

**Comment by thomasrockhu** [comment]
We will look into supporting the arguments from the bash uploader, but as for now, if you are still experiencing issues with timeouts, can you open a support ticket in our [community boards](https://community.codecov.io)?
