### ISSUE TITLE
Remove dot from .codecov.yml default

### ISSUE THREAD

**Issue by thomasrockhu** [codecov/codecov-circleci-orb#31]
https://github.com/codecov/codecov-bash/issues/281

**Comment by drazisil** [comment]
Do we _have_ to have a default? I seem to recall we have exceptions to not add flags if not passed for some other things. The less modification to the bash uploader behavior, the happier we would all be, I think.

**Comment by thomasrockhu** [comment]
@drazisil Unfortunately we either have a default or the parameter is required (https://circleci.com/docs/2.0/reusing-config/#parameter-syntax). I'd rather use a default than make it a required field

**Comment by drazisil** [comment]
We can't do what we are doing with `-f` ? `<< parameters.file >>`

**Comment by thomasrockhu** [comment]
good point @drazisil

**Comment by thomasrockhu** [comment]
Closing by nature of https://github.com/codecov/codecov-bash/blob/master/codecov#L929
