### ISSUE TITLE
Config file not able to be read

### ISSUE THREAD

**Issue by dja** [codecov/codecov-circleci-orb#33]
It looks like the orb can't find the config file when the path specified is not within the project root. Should me a quick fix to the Orb.

<img width="636" alt="Screen Shot 2020-04-20 at 7 49 50 PM" src="https://user-images.githubusercontent.com/1782893/79820022-1ca5e080-8340-11ea-835c-afb3dbd2e97f.png">

Here's my config:
```
      - codecov/upload:
          conf: ~/repo/codecov.yml
          file: coverage/.resultset.json
```

**Comment by thomasrockhu** [comment]
Thanks for opening this issue @dja. As mentioned, the underlying bash uploader does not take `-y` into account, so closing this.
