### ISSUE TITLE
Releases are not tagged, Changelog is missing and Version in README is outdated

### ISSUE THREAD

**Issue by cfra** [codecov/codecov-circleci-orb#46]
In the CircleCI Orb registry, version 1.1.1 is recent.

The main branch `README.md` states 1.1.0 is current.

The latest tag is 1.0.6.

There is no change log.

This makes it somewhat hard for me to understand what code is actually in the Orb and what changed between versions.

It would be great if this could be cleaned up somehow, and if there was some description which place is authoritative.

**Comment by thomasrockhu** [comment]
Thanks @cfra, the releases have been updated and a changelog is added [here](https://github.com/codecov/codecov-circleci-orb/pull/47)

**Comment by cfra** [comment]
PR #47 looks good to me. Thank you for your prompt reply. :+1:
