### ISSUE TITLE
Validating the bash script

### ISSUE THREAD

**Issue by thoward27** [codecov/codecov-circleci-orb#68]
It appears that this orb does not do the necessary steps to validate the bash script as described here:
https://docs.codecov.io/docs/about-the-codecov-bash-uploader#validating-the-bash-script

Based on this security breach:
https://about.codecov.io/security-update/

It seems like the orb should be validating the sha sum.

**Comment by thoward27** [comment]
@thomasrockhu it looks like you're the most active contributor here, apologies if you are not. Can you please take a look at this (if you are involved with this project) and let us know your thoughts?

**Comment by thomasrockhu** [comment]
@thoward27 I will be working on this today, thanks for bringing this up.

**Comment by thoward27** [comment]
@thomasrockhu what are your thoughts on #70? It looks like that would suffice to me.

**Comment by thomasrockhu** [comment]
@thoward27 it's close, I'm going to edit it a little bit and update our docs

**Comment by thoward27** [comment]
@thomasrockhu the dev on the PR was kind enough to take some of my feedback, I believe the orb would work with those changes. Your thoughts?

**Comment by thomasrockhu** [comment]
@thoward27 I posted some changes, but I think it should work.

**Comment by thoward27** [comment]
Resolved by #74
