### ISSUE TITLE
mismatch between downloaded codecov bash script and checksums

### ISSUE THREAD

**Issue by matthewberryman** [codecov/codecov-circleci-orb#92]
It seems something went wrong with your auto-releasing of https://github.com/codecov/codecov-bash , which in turn has broken all versions of this orb that validate the bash script. The orb downloads the latest published version from https://github.com/codecov/codecov-circleci-orb/blob/f37e3b29833bc2136be7232d1e2d09931d67cb13/src/%40orb.yml#L31 which is currently the latest in master of codecov-bash https://github.com/codecov/codecov-bash/blob/c3ccd596467b6c08e6fba7dba6e048dd0e341421/codecov
with checksums https://github.com/codecov/codecov-bash/blob/c3ccd596467b6c08e6fba7dba6e048dd0e341421/SHA1SUM
https://github.com/codecov/codecov-bash/blob/c3ccd596467b6c08e6fba7dba6e048dd0e341421/SHA256SUM
https://github.com/codecov/codecov-bash/blob/c3ccd596467b6c08e6fba7dba6e048dd0e341421/SHA512SUM

However the latest release is a different commit https://github.com/codecov/codecov-bash/releases/tag/1.0.3 with different checksums, and it is these the orb validates against by using the version string https://github.com/codecov/codecov-circleci-orb/blob/f37e3b29833bc2136be7232d1e2d09931d67cb13/src/%40orb.yml#L55 and subsequent lines.

**Comment by thomasrockhu** [comment]
@matthewberryman I have updated to version `1.0.4`, please let me know if you still experience the issue.

**Comment by coconut2015** [comment]
Still broken.

**Comment by matthewberryman** [comment]
@thomasrockhu  Still broken. Looking at your latest deployment logs in CircleCI https://app.circleci.com/pipelines/github/codecov/codecov-bash/413/workflows/4188b6e4-39a1-42bb-93d1-c07028f8ee3d/jobs/1145/parallel-runs/0/steps/0-104 you somehow (and this time it's unclear to me as it should get the latest version from master with `VERSION=1.0.4` in your bash script) still ended up with a `VERSION=1.0.3` so the tagging step again failed but not caught https://github.com/codecov/codecov-bash/issues/446

**Comment by thomasrockhu** [comment]
@matthewberryman @coconut2015 got it, I made a fix to the deployment, is it working now?

**Comment by coconut2015** [comment]
Working fine now for two of my repos.

**Comment by matthewberryman** [comment]
[Working now](https://app.circleci.com/pipelines/github/AcrossTheCloud/TBA21-API/964/workflows/03028b2a-3894-49c2-aa2a-9e56ad1d7e01/jobs/967/parallel-runs/0/steps/0-117), thanks.
