### ISSUE TITLE
Missing: Usage example(s)

### ISSUE THREAD

**Issue by KyleTryon** [codecov/codecov-circleci-orb#94]
At least one usage example is required of all Certified/Partner orbs.
https://circleci.com/docs/2.0/orb-concepts/#usage-examples

Example: 
    source: https://github.com/CircleCI-Public/slack-orb/tree/master/src/examples
    registry: https://circleci.com/developer/orbs/orb/circleci/slack#usage-examples

**Comment by thomasrockhu** [comment]
Fixed via https://github.com/codecov/codecov-circleci-orb/pull/98
